type Query {
  hello: String
  findUsers: [User]!
  findCompanies: [Company]!
  findTasks: [Task]!
  findProjects: [Project]!
}

type Mutation {
  createUser(user: UserInput): User
  createCompany(company: CompanyInput): Company
  createProject(project: ProjectInput): Project
  createTask(task: TaskInput): Task
}

input UserInput {
  company_id: Int!
  firstname: String!
  lastname: String!
}

input CompanyInput {
  owner_id: Int!
  name: String!
}

input ProjectInput {
  company_id: Int!
  name: String!
}

input TaskInput {
  project_id: Int!
  name: String!
}

type User {
  id: Int!
  companyId: Int!
  firstname: String!
  lastname: String!
  company: Company
  project: [Project!]
}

type Company {
  id: Int!
  ownerId: Int!
  name: String!
  owner: User
  users: [User!]
}

type Project {
  id: Int!
  companyId: Int!
  name: String!
  company: Company
  users: [User!]
}

type Task {
  id: Int!
  projectId: Int!
  name: String!
  status: String!
  project: Project
}
